import { Request, Response } from "express";
import * as service from "./private-delegate.service";
const fail = (res: Response, error: any) => res.status(error?.statusCode ?? 400).json({ success: false, message: error?.message ?? "Request failed." });
export async function create(req: Request, res: Response) { try { return res.status(201).json({ success: true, message: "Private delegate badge created.", data: await service.createPrivateDelegate(req.body) }); } catch (e) { return fail(res, e); } }
export async function list(req: Request, res: Response) { try { return res.json({ success: true, data: await service.listPrivateDelegates(req.query.search as string) }); } catch (e) { return fail(res, e); } }
export async function getOne(req: Request, res: Response) { try { return res.json({ success: true, data: await service.getPrivateDelegate(req.params.id as string) }); } catch (e) { return fail(res, e); } }
export async function remove(req: Request, res: Response) { try { await service.deletePrivateDelegate(req.params.id as string); return res.json({ success: true, message: "Private delegate deleted." }); } catch (e) { return fail(res, e); } }
export async function image(req: Request, res: Response) { try { res.type("png").setHeader("Cache-Control", "no-store"); return res.send(await service.generatePrivateDelegateBadge(req.params.id as string)); } catch (e) { return fail(res, e); } }
export async function download(req: Request, res: Response) { try { const d = await service.getPrivateDelegate(req.params.id as string); res.type("png").setHeader("Content-Disposition", `attachment; filename="${d.delegateNumber}.png"`); return res.send(await service.generatePrivateDelegateBadge(d.id)); } catch (e) { return fail(res, e); } }
export async function downloadAll(_req: Request, res: Response) { try { const result = await service.downloadAllPrivateDelegateBadges(); res.type("zip").setHeader("Content-Disposition", `attachment; filename="${result.fileName}"`); result.stream.on("error", () => { if (!res.headersSent) res.status(500).json({ success: false, message: "Badge ZIP generation failed." }); }); return result.stream.pipe(res); } catch (e) { return fail(res, e); } }
